# Generated by Django 3.1.5 on 2022-02-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'WAITING - currently active'), ('Preparation', 'Preparation - superceded by another basket'), ('Delivered', 'Delivered - for items to be purchased later'), ('Cancel', 'Cancel - the basket cannot be modified'), ('Ready', 'Ready')], default='Waiting', max_length=128, verbose_name='Status'),
        ),
    ]
