# Generated by Django 3.1.7 on 2021-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("PREPARATION", "Preparation"),
                    ("READY", "Ready"),
                    ("DELIVER", "Deliver"),
                ],
                default="WAITING",
                max_length=125,
            ),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
